version: '3'

services:
  node:
    build:
      context: node
      dockerfile: Dockerfile
    container_name: node
    image: marciojolima/node
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s docker-entrypoint.sh
    command: npm start
    tty: true
    volumes:
      - ./node/app:/usr/src/app
    depends_on:
      - db
    networks:
      - node-network

  nginx:
    build:
      context: nginx
      dockerfile: Dockerfile
    container_name: nginx
    image: marciojolima/nginx
    tty: true
    ports:
      - "8080:80"
    depends_on:
      - node
    networks:
      - node-network

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - node-network

networks:
  node-network:
    driver: bridge
